In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
import seaborn as sns
df=pd.read_csv("/content/IRIS.csv")

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
from scipy.stats import shapiro

In [ ]:
sub_df1=df['sepal_length']

In [ ]:
sub_df1

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
stat,p=shapiro(sub_df1)
print(" test stat is:",stat)
print("p value is:",p)
if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

 test stat is: 0.9760902723490532
p value is: 0.010181161454691156
data is not normally distributed

In [ ]:
sub_df2=df['sepal_width']

In [ ]:
sub_df2

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [ ]:
stat,p=shapiro(sub_df2)
print(" test stat is:",stat)
print("p value is:",p)
if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

 test stat is: 0.9837916445014413
p value is: 0.07517918532015967
data is normally distributed

In [ ]:
sub_df3=df['petal_length']
stat,p=shapiro(sub_df3)
print(" test stat is:",stat)
print("p value is:",p)
if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

 test stat is: 0.8764246351886722
p value is: 7.545419569615864e-10
data is not normally distributed

In [ ]:
sub_df4=df['petal_width']

In [ ]:
sub_df3

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [ ]:
stat,p=shapiro(sub_df4)
print(" test stat is:",stat)
print("p value is:",p)
if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

 test stat is: 0.9026245656897675
p value is: 1.8647596517271003e-08
data is not normally distributed

In [ ]:
# ONLY SEPAL_LENGTH IS NORMALLY DISTRIBUTED
#USING SKEW

In [ ]:
a=sub_df1.skew()
a
if a==0:
    print("data is normally distributed")
else:
    print("data is not ")

data is not

In [ ]:
b=sub_df2.skew()
b
if b==0:
    print("data is normally distributed")
else:
    print("data is not ")

data is not

In [ ]:
c=sub_df3.skew()
c
if c==0:
    print("data is normally distributed")
else:
    print("data is not ")

data is not

In [ ]:
d=sub_df4.skew()
if d==0:
    print("data is normally distributed")
else:
    print("data is not ")

data is not

In [ ]:
# QUES 2- WHUICH TWO AMONGST THE 4 COLUMNS ARE HIGHLY RELATED ? JUSTIFY USING HYPOTHESIS TESTING

# USING CO RELATION

In [ ]:
import numpy as np
from scipy.stats import pearsonr

In [ ]:
x=df['sepal_length']
y=df['sepal_width']
corr,_=pearsonr(x,y)
print("correlation coefficient is:",corr)

correlation coefficient is: -0.10936924995064937

In [ ]:
r,p=pearsonr(x,y)
print('PERARSON CORELATION TEST:')
print('correlation coefficient is:',r)
print('p value is:',p)

PERARSON CORELATION TEST:
correlation coefficient is: -0.10936924995064937
p value is: 0.18276521527136963

In [ ]:
x1=df['petal_length']
y1=df['petal_width']
corr,_=pearsonr(x,y)
print("correlation coefficient is:",corr)
p

correlation coefficient is: -0.10936924995064937

0.18276521527136963