In [ ]:
import pandas as pd

In [ ]:
## creation of
series=(1,2,3,4,5)
series=pd.Series(series)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
series2=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(series2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
import numpy as np
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [ ]:
series2= pd.Series(array1,index=["jan","feb","march","april","may"])
series2

jan      1
feb      2
march    3
april    4
may      5
dtype: int64

In [ ]:
## creation of series with dictionary
dict1={"india":"new delhi","UK":"london","USA":"Washington DC"}
dict1

{'india': 'new delhi', 'UK': 'london', 'USA': 'Washington DC'}

In [ ]:
series3=pd.Series(dict1)
series3

india        new delhi
UK              london
USA      Washington DC
dtype: object

In [ ]:
s=pd.Series([10,20,30])
s[0]

10

In [ ]:
s1=pd.Series(["new delhi","london","washington DC","Paris"],index=["india","UK","USA","france"])
s1

india         new delhi
UK               london
USA       washington DC
france            Paris
dtype: object

In [ ]:
s1=pd.Series(np.arange(10,20,2))
s1

0    10
1    12
2    14
3    16
4    18
dtype: int64

In [ ]:
import pandas as pd

In [ ]:
seriesA=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
seriesB=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [ ]:
### FOR ADDITION
seriesA+seriesB

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [ ]:
c=seriesA*seriesB
c

a     1
b     4
c     9
d    16
e    25
dtype: int64

In [ ]:
seriesA-seriesB

a    0
b    0
c    0
d    0
e    0
dtype: int64

In [ ]:
import numpy as np

In [ ]:
array1=np.array([1,2,3,4,5])
dFrame=pd.DataFrame(array1)
dFrame

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
import pandas as pd
rs={"nishant":pd.Series([90,91,87],index=["maths","science","hindi"]),
    "amit":pd.Series([90,85,87],index=["maths","science","hindi"]),
    "mithlesh":pd.Series([80,75,96],index=["maths","science","hindi"]),
    "nidhi":pd.Series([98,78,86],index=["maths","science","hindi"])}

In [ ]:
rs=pd.DataFrame(rs)

In [ ]:
rs

         nishant  amit  mithlesh  nidhi
maths         90    90        80     98
science       91    85        75     78
hindi         87    87        96     86

In [ ]:
## operations-adding a new column
rs['vaibhav']=pd.Series([90,85,98],index=["maths","science","hindi"])

In [ ]:
rs=pd.DataFrame(rs)

In [ ]:
rs

         nishant  amit  mithlesh  nidhi  vaibhav
maths         90    90        80     98       90
science       91    85        75     78       85
hindi         87    87        96     86       98

In [ ]:
rs.loc["maths"]=[85,86,87,88,89]

In [ ]:
rs.drop("hindi",axis=0)

         nishant  amit  mithlesh  nidhi  vaibhav
maths         85    86        87     88       89
science       91    85        75     78       85

In [ ]:
#### renaming
rs=rs.rename(columns={"nishant":"nishants","amit":"amits","mithlesh":"mithlehs","nidhi":"nidhis","vaibhav":"vaibhavs"})

In [ ]:
rs

         nishants  amits  mithlehs  nidhis  vaibhavs
maths          85     86        87      88        89
science        91     85        75      78        85
hindi          87     87        96      86        98

In [ ]:
rs.loc["hindi"]

nishants    87
amits       87
mithlehs    96
nidhis      86
vaibhavs    98
Name: hindi, dtype: int64

In [ ]:
### Double click(oe enter) to edit
dataset= {'cars':["BMW","ROLLS ROYCE","PORSCHE"]}
df=pd.DataFrame(dataset)

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
df

          cars
0          BMW
1  ROLLS ROYCE
2      PORSCHE