 **SHAPIRO WILK TEST**

 HO: data is normaly distributed
 HA: data is not normaly distributed

In [ ]:
from scipy.stats import shapiro
data = [1.2,1.4,1.6,1.8,2.0,2.2,2.4,2.6,2.8,3.0]
stats,p= shapiro(data)
print("test stats is:", stats)
print("p-value is:",p)

if p>0.05:
  print("data is normaly distributed")
else:
  print("data is not normaly distributed")

test stats is: 0.9701646110856056
p-value is: 0.8923673061902975
data is normaly distributed

In [ ]:
data = [1.2,1.4,1.6,1.8,2.0,2.2,2.4,2.6,2.8,3.0,500,600,560]
stats,p= shapiro(data)
print("test stats is:", stats)
print("p-value is:",p)

if p>0.05:
  print("data is normaly distributed")
else:
  print("data is not normaly distributed")

test stats is: 0.5566384826539901
p-value is: 2.8332826909001785e-05
data is not normaly distributed

In [ ]:
pp = shapiro(data)[1]
print(pp)

2.8332826909001785e-05

the D'Agostino and Pearson K^2 test

In [ ]:
from scipy.stats import normaltest
data1= data = [1.2,1.4,1.6,1.8,2.0,2.2,2.4,2.6,2.8,3.0]
stat1 ,p1= normaltest(data1)
print("test stats is:", stat1)
print("p-value is:",p1)

if p1>0.05:
  print("data is normaly distributed")
else:
  print("data is not normaly distributed")

test stats is: 0.9782490674104405
p-value is: 0.6131629627834079
data is normaly distributed

/usr/local/lib/python3.10/dist-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  res = hypotest_fun_out(*samples, **kwds)

In [ ]:
import numpy as np
from scipy.stats import pearsonr

# example data
x= [1,2,3,4,5]
y= [2,4,6,8,10]

# pearson correlation
r,p= pearsonr(x,y)


print("Pearsonr correlation Test:")
print("correlation  coefficient :",r)
print("p-value :",p)

# interpretation
if p>0.05:
  print(" the data is lilely not correlated (fail to reject HO).")
else:
  print("the data is correlated (reject HO).")

Pearsonr correlation Test:
correlation  coefficient : 1.0
p-value : 0.0
the data is correlated (reject HO).

In [ ]:
from scipy.stats import spearmanr

# example data
x= [1,2,3,4,5]
y= [5,6,7,8,7]

# spearman correlation
rho, p = spearmanr(x,y)
print("spearman correlation test:")
print("correlation coefficient (p):", rho)
print(f"p-value :",p)

# interpretation
if p>0.05:
  print(" the data is lilely not correlated (fail to reject HO).")
else:
  print("the data is correlated (reject HO).")

spearman correlation test:
correlation coefficient (p): 0.8207826816681233
p-value : 0.08858700531354381
 the data is lilely not correlated (fail to reject HO).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/IRIS.csv")
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
from scipy.stats import normaltest

In [ ]:
sub_df=df["sepal_length"]
sub_df

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
sub_df=df["sepal_width"]
sub_df

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [ ]:
sub_df=df["petal_length"]
sub_df

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [ ]:
sub_df=df["petal_width"]
sub_df

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ...
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal_width, Length: 150, dtype: float64

In [ ]:
stat,p=shapiro(sub_df)
print("test stat is:",stat)
print("p-value is:",p)

if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

test stat is: 0.9026245656897675
p-value is: 1.8647596517271003e-08
data is not normally distributed

In [ ]:
sub_df=df["sepal_length"]
stat,p1=shapiro(sub_df)
print("test stat is:",stat)
print("p-value is:",p1)
if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

test stat is: 0.9760902723490532
p-value is: 0.010181161454691156
data is not normally distributed

In [ ]:
sub_df=df["sepal_length"]
stat,p1=shapiro(sub_df)
print("test stat is:",stat)
print("p-value is:",p1)
if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

test stat is: 0.9760902723490532
p-value is: 0.010181161454691156
data is not normally distributed

In [ ]:
sub_df=df["petal_length"]
stat,p1=shapiro(sub_df)
print("test stat is:",stat)
print("p-value is:",p1)
if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

test stat is: 0.8764246351886722
p-value is: 7.545419569615864e-10
data is not normally distributed

In [ ]:
sub_df=df["petal_width"]
stat,p1=shapiro(sub_df)
print("test stat is:",stat)
print("p-value is:",p1)
if p>0.05:
    print("data is normally distributed")
else:
    print("data is not normally distributed")

test stat is: 0.9026245656897675
p-value is: 1.8647596517271003e-08
data is not normally distributed

In [ ]:
skew = sub_df['sepal_length'].skew()
skew

KeyError: 'sepal_length'

In [ ]:
skew = sub_df['sepal_width'].skew()
skew

KeyError: 'sepal_width'

In [ ]:
skew = sub_df['petal_length'].skew()
skew

KeyError: 'petal_length'

In [ ]:
skew = sub_df['petal_width'].skew()
skew

KeyError: 'petal_width'

In [ ]:
L1={23,32,3,5,7,76,6,6,7,88,7,6,6,5,54,4,34,3,3,3,}
L1
assumed_mean=50
from scipy.stats import ttest_1samp
stats,p_value=ttest_1samp(L1,assumed_mean)
if p_value>0.05:
    print("the mean of sample is same as assumed mean")
else:
    print("the mean of sample is not same as assumed mean")

TypeError: unsupported operand type(s) for /: 'set' and 'int'